config/routes.rb
Rails.application.routes.draw do
  resources :notes

  root "notes#index"

  get "/new", to: "notes#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  def index
    @notes = Note.all
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "\"#{@note.title}\" foi criado(a) com sucesso." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "\"#{@note.title}\" foi editado(a) com sucesso." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "\"#{@note.title}\" foi excluído(a) com sucesso." }
    end
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_header.html.erb
<header class="navbar bg-light">
    <nav class="container">
        <%= link_to "Bloco de Notas", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav">
            <% if is_home %>
                <li class="nav-item">
                    <%= link_to new_path, class: "btn btn-primary" do %>
                        <%= bootstrap_icon "plus-lg" %>
                    <% end %>
                </li>
            <% end %>
            <% if is_showing %>
                <li class="nav-item">
                    <%= link_to edit_note_path(@note), class: "btn btn-primary" do %>
                        <%= bootstrap_icon "pencil-square" %>
                    <% end %>
                    <%= button_to @note, method: :delete, class: "btn btn-danger" do %>
                        <%= bootstrap_icon "trash" %>
                    <% end %>
                </li>
            <% end %>
        </ul>
    </nav>
</header>

app/views/notes/edit.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Editar "<%= @note.title %>" - Bloco de Notas</title>
  </head>
  <body>
    <%= render partial: "header", locals: { is_home: false, is_showing: false } %>

    <main class="container mt-3">
      <h1>Editar "<%= @note.title %>"</h1>

      <%= form_with(model: @note) do |form| %>
        <% if @note.errors.any? %>
          <div class="alert alert-danger">
            <h2><%= pluralize(@note.errors.count, "error") %> não permitiu que a nota seja salva: </h2>

            <ul>
              <% @note.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label "Título", class: "form-label" %>
          <%= form.text_field :title, class: "form-control", placeholder: "Dê um título para identificar sua nota (lembre-se que não pode escrever duas notas com o mesmo nome)", required: true %>
        </div>

        <div class="mb-3">
          <%= form.label "Nota", class: "form-label" %>
          <%= form.text_area :content, rows: 10, class: "form-control", placeholder: "Escreva aqui seus lembretes, pensamentos ou outras coisas..." %>
        </div>

        <%= link_to "Voltar", @note, class: "btn btn-secondary" %>
        <%= form.submit "Editar", class: "btn btn-primary" %>
      <% end %>
    </main>

  </body>
</html>

app/views/notes/index.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Página inicial - Bloco de Notas</title>
  </head>
  <body>
    <%= render partial: "header", locals: { is_home: true, is_showing: false } %>

    <main class="container mt-3">
      <div class="alert alert-success" id="notice">
        <%= notice %>
      </div>

      <h1 class="mb-3">Notas</h1>

      <section class="
        container-fluid
        d-flex
        justify-content-center
        align-items-center
        flex-column
      " id="notas">
        <% @notes.each do |note| %>
          <article class="card mb-3 w-50" id="<%= dom_id note %>">
            <main class="card-body">
              <h5 class="card-title"><%= note.title %></h5>
              <p class="card-text"><%= note.content %></p>
              [...]
            </main>
            <footer class="card-footer d-flex justify-content-center align-items-center">
              <%= link_to "Abrir nota", note, class: "btn btn-primary" %>
            </footer>
          </article>
        <% end %>
      </section>

      <div id="empty-advice" class="alert alert-secondary">
        Está tão vazio por aqui... Que tal criar uma nova nota? Clique no botão <span class="fw-bold">+</span> para começar.
      </div>
    </main>

    <script>
      if (!document.getElementById("notice").innerText) {
        document.getElementById("notice").classList.add("d-none");
      } else {
        setTimeout(() => {
          document.getElementById("notice").style.opacity = "0";
          setTimeout(() => {
            document.getElementById("notice").classList.add("d-none");
          }, 300);
        }, 2500);
      }

      if (document.getElementById("notas").innerText) {
        document.getElementById("empty-advice").classList.add("d-none");
      }
    </script>
  </body>
</html>

app/views/notes/new.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Criar nota - Bloco de notas</title>
  </head>
  <body>
    <%= render partial: "header", locals: { is_home: false, is_showing: false } %>

    <main class="container mt-3">
      <h1>Criar nota</h1>

      <%= form_with(model: @note) do |form| %>
        <% if @note.errors.any? %>
          <div class="alert alert-danger">
            <h2><%= pluralize(@note.errors.count, "error") %> não permitiu que a nota seja salva:</h2>

            <ul>
              <% @note.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label "Título", class: "form-label" %>
          <%= form.text_field :title, class: "form-control", placeholder: "Dê um título para identificar sua nota (lembre-se que não pode escrever duas notas com o mesmo nome)", required: true %>
        </div>

        <div class="mb-3">
          <%= form.label "Nota", class: "form-label" %>
          <%= form.text_area :content, rows: 10, class: "form-control", placeholder: "Escreva aqui seus lembretes, pensamentos ou outras coisas..." %>
        </div>

        <%= link_to "Voltar", root_path, class: "btn btn-secondary" %>
        <%= form.submit "Criar", class: "btn btn-primary" %>
      <% end %>
    </main>
  </body>
</html>

app/views/notes/show.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title><%= @note.title %> - Bloco de Notas</title>
  </head>
  <body>
    <%= render partial: "header", locals: { is_home: false, is_showing: true } %>

    <main class="container mt-3">
      <div class="alert alert-success" id="notice">
        <%= notice %>
      </div>

      <h1><%= @note.title %></h1>
      <p class="note-content"><%= @note.content %></p>

    </main>

    <script>
      if (!document.getElementById("notice").innerText) {
        document.getElementById("notice").classList.add("d-none");
      } else {
        setTimeout(() => {
          document.getElementById("notice").style.opacity = "0";
          setTimeout(() => {
            document.getElementById("notice").classList.add("d-none");
          }, 300);
        }, 2500);
      }
    </script>
  </body>
</html>